# Imatinib

### Libraries

In [1]:
import sys

sys.path.append("..")

In [2]:
import open3d as o3d
import numpy as np
import seaborn as sns
import pandas as pd

from io import StringIO

import py3Dmol

from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import PandasTools

from open3d.web_visualizer import draw

import ipywidgets as widgets
from IPython.display import HTML

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


INFO - 2021-07-20 12:42:49,855 - __init__ - Enabling RDKit 2021.03.3 jupyter extensions


[Open3D INFO] Resetting default logger to print to terminal.


In [3]:
from score_pcd import fit_and_score

## Create Point Clouds

Create PCD files for imatinib using Singularity container:

In [4]:
%%bash

singularity run --nv --app python ../development/densitymatch.sif \
    ../molgrid_to_pcd.py ../files/imatinib.sdf -m ../files/ligmap -r 0.5 -o ligands/imatinib.pcd
singularity run --nv --app python ../development/densitymatch.sif \
    ../molgrid_to_pcd.py ../files/imatinib_moved.sdf -m ../files/ligmap -r 0.5 -o ligands/imatinib_moved.pcd
singularity run --nv --app python ../development/densitymatch.sif \
    ../molgrid_to_pcd.py ../files/imatinib_part.sdf -m ../files/ligmap -r 0.5 -o ligands/imatinib_part.pcd

Using a Singularity container to run `molgrid_to_pcd.py` is needed because of a [`openbabel`/`molgrid` incomparibility from PyPI](https://github.com/gnina/libmolgrid/issues/62). `molgrid` and `openbabel` in the Singularity container are both installed form source.

## Imatinib Alignment

Load SDF and PCD files for imatibib (original coordinates and moved coordinates):

In [5]:
files = ["imatinib.pcd", "imatinib_moved.pcd"]

pcds = []
mols = []
for f in files:
    pcd = o3d.io.read_point_cloud(os.path.join("ligands", f))
    pcds.append(pcd)

    s = Chem.SDMolSupplier(os.path.join("../files",f.replace(".pcd", ".sdf")))
    mol = next(s)
    mols.append(mol)

In [6]:
print(pcds, mols)

[PointCloud with 1284 points., PointCloud with 1239 points.] [<rdkit.Chem.rdchem.Mol object at 0x7fca537ba1c0>, <rdkit.Chem.rdchem.Mol object at 0x7fca53e965d0>]


We can visualize the point clouds using Open3D (does not work on VSCode Jupyter extension for some reason...):

In [7]:
# This fails in VSCode
#draw(pcds[0])
#draw(pcds[1])

We can visualize the molecules using `py3Dmol`:

In [8]:
p = py3Dmol.view()

for i, mol in enumerate(mols):
    mb = Chem.MolToMolBlock(mol, confId=0)
    p.addModel(mb,'sdf')

# Select model in order of additon with the following selection: {"model": index}
p.setStyle({"model": 0}, {'stick':{'colorscheme':'lightgreyCarbon'}})
p.setStyle({"model": 1}, {'stick':{"colorscheme": "greyCarbon"}})


p.zoomTo()
p.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

We can now fit the imatinib (as point cloud) into imatinib and score the alignmenment:

In [9]:
gfit, cfit, tran = fit_and_score(pcds, voxel_size=0.5, threshold=0.5)

In [10]:
print("GFIT:", gfit.fitness)
print("CFIT:", cfit.fitness)
print("transformation:\n", tran)

GFIT: 0.8037383177570093
CFIT: 0.9587227414330218
transformation:
 [[ -0.22349726  -0.96928013  -0.1026889    4.20426439]
 [ -0.72704402   0.09561121   0.67990109   0.47138655]
 [ -0.6491964    0.22661538  -0.72607817 -10.6567969 ]
 [  0.           0.           0.           1.        ]]


The alignment also returns a $4\times 4$ representing the affine transformation (rotation and translation) needed to superimpose the two point clouds (and molecules). The affine transformation is defined by the following $4\times 4$ matrix:
$$
    A = \begin{pmatrix}
        r_{00} & r_{01} & r_{02} & t_0 \\
        r_{10} & r_{11} & r_{12} & t_1 \\
        r_{20} & r_{21} & r_{22} & t_2 \\
        0 & 0 & 0 & 1 \\
    \end{pmatrix}
$$
For an affine tranfromation $A$ represented in this way, the transformed points $\mathbf{x}'$ are given by:
$$
    \begin{pmatrix}
        x' \\ y' \\ z' \\ 1
    \end{pmatrix} = 
    A \begin{pmatrix}
        x \\ y \\ z \\ 1
    \end{pmatrix}
$$

We can now transform the corrdinates of the RDKit molecules in order to check the superimposition:

In [11]:
# Molecule to transform
molid = 0

In [12]:

# Select coordinates to transform
coords = mols[molid].GetConformer(0).GetPositions()

# Augment coordinates with ones
coords_aug = np.ones((coords.shape[0], 4))
coords_aug[:,:3] = coords

# Transform coordinates (using broadcasting)
coords_new = np.matmul(tran, coords_aug.T)[:3,:].T

In [13]:
# Add new coordinates as additional conformer

n_atoms = mols[molid].GetNumAtoms()
conf = Chem.Conformer(n_atoms)
for i in range(n_atoms):
    conf.SetAtomPosition(i, coords_new[i,:])

_ = mols[molid].AddConformer(conf, assignId=True)

We can now visually check the alignment:

In [14]:
p = py3Dmol.view()

for i, mol in enumerate(mols[:2]):
    confid = 0
    if i == molid:
        confid = 1
    
    p.addModel(Chem.MolToMolBlock(mol, confId=confid),'sdf')

p.setStyle({"model": 0}, {'stick':{'colorscheme':'redCarbon'}})
p.setStyle({"model": 1}, {'stick':{'colorscheme':'lightgreyCarbon'}})


p.zoomTo()
p.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [15]:
#print(Chem.MolToMolBlock(mols[0],confId=0))
#print(Chem.MolToMolBlock(mols[0],confId=1))
#print(Chem.MolToMolBlock(mols[1],confId=0))

## Imatininib Alignment with Subset

We can now try to align a subset (a small fragment) of imatinib into the whole molecule:

In [16]:
files = ["imatinib.pcd", "imatinib_part.pcd"]

pcds = []
mols = []
for f in files:
    pcd = o3d.io.read_point_cloud(os.path.join("ligands", f))
    pcds.append(pcd)

    s = Chem.SDMolSupplier(os.path.join("../files",f.replace(".pcd", ".sdf")))
    mol = next(s)
    mols.append(mol)

In [17]:
print(pcds, mols)

[PointCloud with 1284 points., PointCloud with 477 points.] [<rdkit.Chem.rdchem.Mol object at 0x7fca537b48f0>, <rdkit.Chem.rdchem.Mol object at 0x7fca537be800>]


In [18]:
# This fails in VSCode
#draw(pcds[0])
#draw(pcds[1])

We can see that initially the fragment is completely misaligned:

In [19]:
p = py3Dmol.view()

for i, mol in enumerate(mols):
    mb = Chem.MolToMolBlock(mol, confId=0)
    p.addModel(mb,'sdf')
    
p.setStyle({"model": 0}, {'stick':{'colorscheme':'lightgreyCarbon'}})
p.setStyle({"model": 1}, {'stick':{'colorscheme':'redCarbon'}})

p.zoomTo()
p.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

In [20]:
gfit, cfit, tran = fit_and_score(pcds, voxel_size=0.5, threshold=0.5)

In [21]:
print("GFIT:", gfit.fitness)
print("CFIT:", cfit.fitness)
print("transformation:\n", tran)

GFIT: 0.25778816199376947
CFIT: 0.309190031152648
transformation:
 [[  0.90220409  -0.40111599   0.15853624   4.49435218]
 [  0.41668442   0.90550173  -0.08025397 -10.49725383]
 [ -0.11136369   0.13846504   0.98408615   0.25114666]
 [  0.           0.           0.           1.        ]]


In [22]:
# Molecule to transform
molid = 0

# Get coordinates to transform
coords = mols[molid].GetConformer(0).GetPositions()

# Augment coordinates with ones
coords_aug = np.ones((coords.shape[0], 4))
coords_aug[:,:3] = coords

coords_new = np.matmul(tran, coords_aug.T)[:3,:].T

# Add new coordinates as conformer
n_atoms = mols[molid].GetNumAtoms()
conf = Chem.Conformer(n_atoms)
for i in range(n_atoms):
    conf.SetAtomPosition(i, coords_new[i,:])

_ = mols[molid].AddConformer(conf, assignId=True)

We can now verify how the fragment was aligned to the original molecule:

In [23]:
p = py3Dmol.view()

for i, mol in enumerate(mols[:2]):
    confid = 0
    if i == molid:
        confid = 1
    
    p.addModel(Chem.MolToMolBlock(mol, confId=confid),'sdf')

p.setStyle({"model": 0}, {'stick':{'colorscheme':'lightgreyCarbon'}})
p.setStyle({"model": 1}, {'stick':{'colorscheme':'redCarbon'}})

p.zoomTo()
p.show()

You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: 
 jupyter labextension install jupyterlab_3dmol

Unfortunately the point cloud alignment is non-deterministic (it is impossible to set a random seed, see [open3d/#288](https://github.com/intel-isl/Open3D/issues/288) and [open3d/#1263](https://github.com/intel-isl/Open3D/issues/1263)) and therefore sometimes the alignment is extremely good while other times it is not.